_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.9
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
model:
    value: LinearRegression
